language: python

python:
  - "2.7_with_system_site_packages"

env:
  - TOX_ENV=py27
  - TOX_ENV=flake8

install:
  - "sudo apt-get update || true"
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"

deploy:
  provider: pypi
  user: janez.troha
  password:
    secure: efknTHUuHpc4UPcy2u90pBWuEFMiX1I209wa5ZQbr1A0B9VPcwTxi4kvnfqqOV/PBGT58Hkx1/hltZ/ORBufEWUKQWzBxtPXdPfcHVXu4wdWrZycLXt6mKhynPW/qDKlPEUv3yUTPFlH8e2kp3eSyuWI4K/yaZ050f2hvjzX78Y=
  on:
    tags: true
    repo: dz0ny/leapcast
